FROM us-central1-docker.pkg.dev/andromeda-456013/amber/cuda-with-python
LABEL maintainer="Sergey Grigoriev <s.a.grigoriev@gmail.com>"
LABEL description="Automatik1111 web UI for Stable Diffusion"

COPY entry.sh .
ENTRYPOINT ["./entry.sh"]
